project:
  name: "SPECTRA_replogle_correct"
  seed: 42
  deterministic: False
  use_wandb: True

data:
  adata_path: "/scratch/michele.calabro/gears/VCC/SPECTRA/data/replogle_k562_filtered.h5ad"
  gene_list_path: "/scratch/michele.calabro/gears/VCC/SPECTRA/data/gene_list-replogle.txt"
  network_path: "/scratch/michele.calabro/gears/VCC/SPECTRA/data/guanlab_replogle_pruned_reciprocal_mst.tsv"
  scgpt_embeddings_path: "/scratch/michele.calabro/gears/VCC/SPECTRA/data/scGPT_embeddings_all_genes.pkl"
  gene_weights_path: "/scratch/michele.calabro/gears/VCC/SPECTRA/data/gene_weights-replogle_200_min.pkl"

model:
  architecture: "FAGCN_3_layers_rep"
  conv_type: 'FAGCN'
  residual_weight: 0.9
  n_channels: 16
  dropout_p: 0.14
  num_node_features: 1

training:
  batch_size: 48
  lr: 0.001
  n_epochs: 20
  alpha: 3.
  beta: 0.001
  gamma: 1.0
  eta: 1.0
  test_ratio: 0.2
  val_ratio: 0.1