project:
  name: "SPECTRA_new_FUNGI_replogle"
  seed: 42
  deterministic: False
  use_wandb: True

data:
  adata_path: "/scratch/michele.calabro/gears/VCC/SPECTRA/data/replogle_k562_filtered.h5ad"
  gene_list_path: "/scratch/michele.calabro/gears/VCC/SPECTRA/data/gene_list-replogle.txt"
  network_path: "/scratch/michele.calabro/gears/VCC/SPECTRA/data/guanlab_replogle_pruned_reciprocal_mst.tsv"
  scgpt_embeddings_path: "/scratch/michele.calabro/gears/VCC/SPECTRA/data/scGPT_embeddings_all_genes.pkl"
  gene_weights_path: "/scratch/michele.calabro/gears/VCC/SPECTRA/data/gene_weights-replogle_200_min.pkl"

model:
  architecture: "FUNGI_FAGCN_replogle_2layers"
  conv_type: 'FAGCN'
  residual_weight: 0.37
  n_channels: 48
  dropout_p: 0.19
  num_node_features: 1

training:
  batch_size: 16
  lr: 0.001
  n_epochs: 20
  alpha: 2.5
  beta: 0.0005
  gamma: 1.5
  eta: 1.2
  test_ratio: 0.2
  val_ratio: 0.1