project:
  name: "SPECTRA_vcc_new_loss"
  seed: 42
  deterministic: False
  use_wandb: True

data:
  adata_path: "/scratch/michele.calabro/gears/VCC/SPECTRA/data/adata_vcc.h5ad"
  gene_list_path: "/scratch/michele.calabro/gears/VCC/SPECTRA/data/gene_list-vcc.txt"
  network_path: "/scratch/michele.calabro/gears/VCC/SPECTRA/data/FUNGI_new_vcc.tsv"
  scgpt_embeddings_path: "/scratch/michele.calabro/gears/VCC/SPECTRA/data/scGPT_embeddings_all_genes.pkl"
  gene_weights_path: "/scratch/michele.calabro/gears/VCC/SPECTRA/data/gene_weights-vcc.pkl"

model:
  architecture: "FUNGI_FAGCN_3layers_fixed_VCC"
  conv_type: 'FAGCN'
  residual_weight: 0.6
  n_channels: 16
  dropout_p: 0.1
  num_node_features: 1

training:
  batch_size: 48
  lr: 0.001
  n_epochs: 25
  alpha: 3.
  beta: 0.001
  gamma: 1.0
  eta: 1.0
  test_ratio: 0.2
  val_ratio: 0.1