project:
  name: "SPECTRA_new_FUNGI"
  seed: 42
  deterministic: False
  use_wandb: True

data:
  adata_path: "/scratch/michele.calabro/gears/VCC/SPECTRA/data/adata_vcc.h5ad"
  gene_list_path: "/scratch/michele.calabro/gears/VCC/SPECTRA/data/gene_list-vcc.txt" #not necessary
  network_path: "/scratch/michele.calabro/gears/VCC/SPECTRA/data/FUNGI_new_vcc.tsv"
  scgpt_embeddings_path: "/scratch/michele.calabro/gears/VCC/SPECTRA/data/scGPT_embeddings_all_genes.pkl"
  gene_weights_path: "/scratch/michele.calabro/gears/VCC/SPECTRA/data/gene_weights-vcc.pkl" #not necessary

model:
  architecture: "FUNGI_FAGCN_vcc_final"
  conv_type: 'FAGCN'
  residual_weight: 0.3589162920376502
  n_channels: 32
  dropout_p: 0.3746613855008784
  num_node_features: 1

training:
  batch_size: 16
  lr: 0.001
  n_epochs: 20
  alpha: 3.6299253308147623
  beta: 0.010236970494169488
  gamma: 0.9808048429425212
  eta: 1.6011257206059
  test_ratio: 0.2
  val_ratio: 0.1