project:
  name: "SPECTRA_wilconxon"
  seed: 42
  deterministic: False
  use_wandb: True

data:
  adata_path: "/scratch/michele.calabro/gears/VCC/SPECTRA/data/adata_vcc.h5ad"
  gene_list_path: "/scratch/michele.calabro/gears/VCC/SPECTRA/data/gene_list-vcc.txt"
  network_path: "/scratch/michele.calabro/gears/VCC/SPECTRA/data/vcc_4/VCC_4_no_chitin.tsv"
  scgpt_embeddings_path: "/scratch/michele.calabro/gears/VCC/SPECTRA/data/scGPT_embeddings_all_genes.pkl"
  gene_weights_path: "/scratch/michele.calabro/gears/VCC/SPECTRA/data/gene_weights-vcc.pkl"

model:
  architecture: "final_wilconxon"
  conv_type: 'FAGCN'
  residual_weight: 0.7
  n_channels: 64
  dropout_p: 0.3
  num_node_features: 1

training:
  batch_size: 24
  lr: 0.001
  n_epochs: 20
  alpha: 1.8
  beta: 0.01
  gamma: 2.6
  eta: 3.3
  test_ratio: 0.2
  val_ratio: 0.1